#Whether or not to enable crafting
Crafting: true
#If crafting is enabled, this defines the recipe.
#The numbers represent the slots of the crafting table in 3 rows. The top left corner
#would be 1 and the bottom right 9
#Values for materials can be found here:

#Make sure they are typed EXACTLY as shown!
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
Pack Recipe:
  1: LEATHER
  2: STRING
  3: LEATHER
  4: STRING
  5: CHEST
  6: STRING
  7: LEATHER
  8: STRING
  9: LEATHER

#Key value pairs for upgrading packs. Each pack can be upgraded from levels 1-5 incrementally,
#each level giving you 9 more slots. The Key-Value pairs represent Materials and amounts of those materials
#Material values can be found here
#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Make sure they are typed EXACTLY as shown!
Pack Upgrades:
  1->2:
    IRON_INGOT: 16
    STRING: 16
  2->3:
    REDSTONE: 16
    STRING: 16
  3->4:
    GOLD_INGOT: 16
    STRING: 16
  4->5:
    DIAMOND: 16
    STRING: 16

#Default name to give any given pack-Use @p to reference the pack creator, and @l to reference the level!
Default Name: "&7Cool Custom-Named &4Pack!-Owned by @p. Level: @l"

#Default Lore to give a pack. You can use @p and @l down here as well!
Default Lore:
  - "Default Lore is cool"
  - "You might want to edit me in the highly customizable config!"
  - "&4-Yona168 :)"

